FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o migrator ./cmd/migrator

FROM alpine:latest

WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/migrator /app/migrator
COPY config.yaml /app/config.yaml
COPY migrations /app/migrations

ENTRYPOINT ["/app/migrator"]